%%{init: { 'logLevel': 'debug', 'theme': 'default' } }%%
timeline
    title Tool Calling Series 
    Create utils: 👉Jupyter Utils 
         : 👉 Logging 
         : 👉 Colab 
    Use Utils: Import utils and logs
             : Create OpenAI utils
             : Colab Secrets OpenAI Key     
    Tool-Calling Infrastructure : PyDantic based 
                                : Native Python Functions                                   
    Using Tools : Single tool in Prompt 
                : Chain tools in a single prompt 
                : ReAct prompt, Tavily
                : Considerations