@startuml
start
:ReAct loop;
repeat
:Assistant response
 ↪ ReAct protocol;
if (Has **ReAct / Answer** ?) then (<color:green> **yes**)
  : Terminate loop;
#lightgreen  : return answer;
  end
else (<color:orange> **no**)  
#yellow  : **ReAct / Action**\n **ReAct / Action Input**;
note right
  The ReAct prompt will 
  require //action input//
  to be stringified JSON
end note
#orange  : **Invoke tool**\n  ↪ response or error\n  ↪ Observation;
endif
backward: continue loop;
@enduml