
%% These are one of 'base', 'forest', 'default', 'base', 'dark', `neutral`
%%{init: { 'logLevel': 'debug', 'theme': 'default' } }%%
timeline
    title Tool Calling Series 
    Create utils: ✔️ Jupyter Utils 
         : ✔️ Logging 
         : ✔️ Colab 
    Use Utils: ✔️ Import utils and logs
             : ✔️ OpenAI Single shot prompting
             : ✔️ OpenAI chat
             : ✔️ Colab Secrets OpenAI Key     
    Tool-Calling : ✔️ Tools + LLMs
                 : ✔️ PyDantic based 
                 : ✔️ Native Python Functions
                 : ✔️ Single tool in Prompt 
                 : ✔️ Chain tools in a single prompt                 
    ReAct        : 👉 ReAct 
                 : 👉 Tools in ReAct
                 : 👉 Search tool
                 : 👉 Tools considerations