@startuml
start
: ReAct Prompt
  +
 Allowed Actions  (tools);
repeat 
:Thought; 
:Action;
switch (Observation?)
  case (<color:red> **No Such Action**)
    #lightpink : Hallucinated an action\n;
    #lightyellow :**LLMOps**\nSurface this\nCandidate action to consider\nin next rev of prompt\n\n;
    #orange :**Next Thought Expection**\n\n**LLM Backtracks**\nPicks an actual available action\nor gives up;    
  case (<color:red> **Action errors**)
    #lightpink :Hallucinated action parameters\nor tool execution error;
    #lightyellow :**LLMOps**\nSurface this!\nIf hallucinated parameters\nconsider improving clarity of\n - tool description\n - parameter field descriptions;
    #orange :**Next Thought Expectation**\n\n**LLM Backtracks**\nFix parameters and repeat\nor pick another action;
  case (<color:green> **Action Succeeded**)  
    #lightgreen :Syntactically correct action\nand parameters;
    switch (**LLM Judgement**\n      **Progress ?**)
        case (<color:green> **Progressing**)
          #orange :**Next Thought Expectation**\n\n**LLM Logic**\nGenerates a logical next step;
          case (<color:red> **Not Progressing**)
          #orange :**Next Thought Expectation**\n\n**LLM Backtracks**\nTries a different action\nor different parameters;
    endswitch
endswitch

repeatwhile (**Have Answer?**)

#lightgreen:✔️ Terminate loop with Answer;

stop

@enduml