@startmindmap
title = The ReAct loop and it's mapping to chat roles
*[#orange] = ReAct

**[#yellow]:== Concepts
and Components;

***:=== Prompt
Our ask of the LLM. This includes the list of 
allowable actions that it can take;
***:=== Actions
Action is a **verb** that the LLM needs 
to **do** in the process of building out 
the response to the prompt.

An action is simply the LLM Tool we have 
seen before: the //function call//;

***:=== Observations
The **outcome of an action** is called
the observation. This was named to imply 
that the LLM is //doing stuff// and then 
//observing// what happens.

In tool terms, this is the return value of 
the function call;

***:=== Answer
Once the LLM has taken all the actions it 
needs to and made the consequent 
observations it finally decides that it has 
enough information to provide a final answer;

' The Prompt -----------------
**:== 1️⃣ Prompt the LLM
Compose these parts;
*** === The main ask
***[#yellow]:=== COT exemplars
----
in-context learning: one or multi-shot
  - describe **action, observation & result**
  - Ask to keep acting and observing till answer
  - Tell it when and how to terminate;
***:=== list of allowed Actions
The standard LLM tools;
***:=== Repeat the ask  
in terms of the Act-Observe loop;

' The Loop  -----------------
** == 2️⃣ Loop
***:=== LLM 
↪ Invoke **action(parameters)**;
***:=== Client
   execute **action(parameters)** 
   **result | error** → Observation
↩ Observation;

** == 3️⃣ Answer

left side
** Action is a tool
**:Action list provided in prompt
is a simplified version of the tool 
schema used for tools;

' role = assistant --------------
**[#lightyellow]:== chat role ⇒ **assistant**
----
👉COT instructions should ask 
for a specific format of the 
**Action** and **Answer**

This will guide the regex on the 
content of the assistant response

 **^(** 
 **     Thought ** 
 **    |Action ** 
 **    |Action Input ** 
 **    |Answer ** 
 **  )\s*:\s*(.*?)$ **;

***_ content ⇒ **Thought**
***_ content ⇒ **Action**
***_ content ⇒ **Action Input**
***_ content ⇒ **Answer**
***_:
OpenAI sometimes qualifies the action 
 name with **function[s].** . A hint that 
 they are generating a python module-like
 artifact called **functions** to hold all 
 the supplied actions.

    //Action//: functions.my_action;    

' role = user --------------
**[#lightyellow] == chat role ⇒ **user** 
***_ content ⇐ **Initial Pompt** 
***_ content ⇐ **Observation** 

' role = user --------------
**[#lightyellow]:== chat role ⇒ **tool_call | tool** 

COT instructions ask for //Action// 
and //Action Input// and these come 
in via the usual //role=assistant// 
response.

However, some models might utilize 
the //tool_call// role to response 
and instead of an observation expect a 
//tool// response.;

@endmindmap