---
name: ~
applications:
  seldon-controller-manager:
    annotations: ~
    channel: ~
    charm: "cs:seldon-core-50"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  dex-auth:
    annotations: ~
    channel: ~
    charm: "cs:dex-auth-60"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  mlmd:
    annotations: ~
    channel: ~
    charm: "cs:mlmd-5"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  kfp-viz:
    annotations: ~
    channel: ~
    charm: "cs:kfp-viz-8"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  istio-pilot:
    annotations: ~
    channel: ~
    charm: "cs:istio-pilot-20"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options:
      default-gateway: kubeflow-gateway
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  jupyter-ui:
    annotations: ~
    channel: ~
    charm: "cs:jupyter-ui-10"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  minio:
    annotations: ~
    channel: ~
    charm: "cs:minio-55"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  tfjob-operator:
    annotations: ~
    channel: ~
    charm: "cs:tfjob-operator-1"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  kfp-persistence:
    annotations: ~
    channel: ~
    charm: "cs:kfp-persistence-9"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  argo-controller:
    annotations: ~
    channel: ~
    charm: "cs:argo-controller-51"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  kfp-db:
    annotations: ~
    channel: ~
    charm: "cs:~charmed-osm/mariadb-k8s-35"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options:
      database: mlpipeline
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  kfp-schedwf:
    annotations: ~
    channel: ~
    charm: "cs:kfp-schedwf-9"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  istio-ingressgateway:
    annotations: ~
    channel: ~
    charm: "cs:istio-ingressgateway-20"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  kubeflow-dashboard:
    annotations: ~
    channel: ~
    charm: "cs:kubeflow-dashboard-56"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  kubeflow-volumes:
    annotations: ~
    channel: ~
    charm: "cs:kubeflow-volumes-0"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  kfp-api:
    annotations: ~
    channel: ~
    charm: "cs:kfp-api-12"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  kfp-ui:
    annotations: ~
    channel: ~
    charm: "cs:kfp-ui-12"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  kubeflow-profiles:
    annotations: ~
    channel: ~
    charm: "cs:kubeflow-profiles-52"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  pytorch-operator:
    annotations: ~
    channel: ~
    charm: "cs:pytorch-operator-53"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  kfp-viewer:
    annotations: ~
    channel: ~
    charm: "cs:kfp-viewer-9"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  jupyter-controller:
    annotations: ~
    channel: ~
    charm: "cs:jupyter-controller-56"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  admission-webhook:
    annotations: ~
    channel: ~
    charm: "cs:admission-webhook-10"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
  oidc-gatekeeper:
    annotations: ~
    channel: ~
    charm: "cs:oidc-gatekeeper-54"
    config: {}
    constraints: ~
    devices: {}
    endpoint_bindings: {}
    expose: false
    options: {}
    placement: ~
    plan: ~
    requires_trust: false
    resources: {}
    scale: 1
    series: ~
    source: ~
    storage: {}
    to: []
bundle: kubernetes
description: ~
relations:
  - - argo-controller
    - minio
  - - "dex-auth:oidc-client"
    - "oidc-gatekeeper:oidc-client"
  - - "istio-pilot:ingress"
    - "dex-auth:ingress"
  - - "istio-pilot:ingress"
    - "jupyter-ui:ingress"
  - - "istio-pilot:ingress"
    - "kfp-ui:ingress"
  - - "istio-pilot:ingress"
    - "kubeflow-dashboard:ingress"
  - - "istio-pilot:ingress"
    - "kubeflow-volumes:ingress"
  - - "istio-pilot:istio-pilot"
    - "istio-ingressgateway:istio-pilot"
  - - "istio-pilot:ingress"
    - "oidc-gatekeeper:ingress"
  - - "istio-pilot:ingress-auth"
    - "oidc-gatekeeper:ingress-auth"
  - - kfp-api
    - kfp-db
  - - "kfp-api:kfp-api"
    - "kfp-persistence:kfp-api"
  - - "kfp-api:kfp-api"
    - "kfp-ui:kfp-api"
  - - "kfp-api:kfp-viz"
    - "kfp-viz:kfp-viz"
  - - "kfp-api:object-storage"
    - "minio:object-storage"
  - - "kfp-ui:object-storage"
    - "minio:object-storage"
  - - kubeflow-profiles
    - kubeflow-dashboard
series: ~